DP-48772: shout out to terraform (#317)
Callers of the `gha-role` and `gha_pipeline` modules currently run into
the following error when creating _and_ attaching an IAM policy in the
same terraform application:

```
 Error: Invalid for_each argument

  on .terraform/modules/common.poc_self_hosted_gh_runner_apply/gha-role/main.tf line 40, in resource "aws_iam_role_policy_attachment" "policy_attachments":
  40:   for_each   = toset(var.policy_arns)
    ├────────────────
    │ var.policy_arns is list of string with 2 elements

The "for_each" set includes values derived from resource attributes that
cannot be determined until apply, and so Terraform cannot determine the full
set of keys that will identify the instances of this resource.

When working with unknown values in for_each, it's better to use a map value
where the keys are defined statically in your configuration and where only
the values contain apply-time results.
```

This small PR corrects that. I've tested it here:
https://github.com/massgov/digital-ssr-infrastructure/actions/runs/34623914188/job/103344277072