DP-43822: Fix newline character parsing in manifest (#276)
Ticket: https://massgov.atlassian.net/browse/DP-43822

Changelog: Fix parsing of docs.manifest file ending in a newline
character and update terraform docs to fix PR checks


### Context

After updating the docs.manifest file from linux in
https://github.com/massgov/virtual-assistant and merging, there was a
failure to deploy.

```
Error: Error in function call

  on .terraform/modules/tags/tagging/s3.tf line 15, in resource "aws_s3_object" "files":
  15:   etag   = filemd5("${local.relative_path}${replace(replace(each.value, "../", ""), "./", "")}") # Use MD5 hash to detect changes
    ├────────────────
    │ while calling filemd5(path)
    │ each.value is ""
    │ local.relative_path is "../../../"

Call to function "filemd5" failed: read ../../..: is a directory.
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

This is because the newline character was added to the end of the file,
causing the parsing logic to treat `""` as a value, causing the relative
path to be a directory.

It's a posix standard for text files to end in a newline character per
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
, so this should be supported.

It looks like the CHANGELOG.md file became out of sync with the
releases. This PR doesn't fix it, but I'm happy to reconcile that if
it's preferred.